### ISSUE TITLE
[1.5-11] Random CME on panels

### ISSUE THREAD

**Issue by MrGraphic** [malte0811/IndustrialWires#10]
Getting client side crashes on different panel configurations. Crashes happens completly randomly when I try to operate elements.
```java
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at malte0811.industrialWires.controlpanel.PanelUtils.generateQuads(PanelUtils.java:83)
	at malte0811.industrialWires.client.panelmodel.PanelModel$AssembledBakedModel.func_188616_a(PanelModel.java:126)
	at malte0811.industrialWires.client.panelmodel.PanelModel.func_188616_a(PanelModel.java:74)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
at java.lang.Thread.run(Unknown Source)
````
Full log https://gist.github.com/MrGraphic/ff3ce42d7a30ee348043c60c62622023
Also noticed slight fps drop when looking at panels in vertical position within operational range .

**Comment by malte0811** [comment]
I'll look into this tomorrow, the first bug should be fixable. Regarding the second bug: "Operational range" means that you are close enough for the black outline/hitbox to show? And this only happens with panels placed against a wall?

**Comment by MrGraphic** [comment]
ad. 1 no need to touch panel, happens also when indicators state changes.
ad. 2 yes, exactly that kind of "range". I have one panel on the ground and second one on the wall against panel connector. The first seems to be ok the second causes that drop.

**Comment by malte0811** [comment]
I have fixed the first issue. The second one I am not able to reproduce unless you are talking about a ridiculously small drop (~5 frames at 100 FPS (with VSync disabled and a much less powerful computer than yours)). I'll do some optimization regarding the hitboxes, I don't know whether it will help at all.

**Comment by malte0811** [comment]
I have made some improvements, no idea whether they will help. The code related to hitbox rendering changed quite a bit when I implemented tilted panels, that might have helped too.

**Comment by MrGraphic** [comment]
Thanks for a fix.
About that fps drop, no idea what is going on ( labels ? ) - both has been rearranged few times:
![2017-07-03_21 23 26](https://user-images.githubusercontent.com/4780141/27807049-3b84b0ba-6036-11e7-87f8-70dfccd48a48.png)
![2017-07-03_21 23 40](https://user-images.githubusercontent.com/4780141/27807055-456ddf16-6036-11e7-9232-ac010098844c.png)

**Comment by malte0811** [comment]
Yep, it is the labels. I completely forgot to add equals/hashCode methods for them and never noticed it since they are "boring" and I don't use them in dev... I'll get a new build out tomorrow to fix this. The build I published today won't do anything about the lag since I looked in the completely wrong place.

**Comment by MrGraphic** [comment]
Yeah, sorry for not showing this in the first place.
