### ISSUE TITLE
[1.12.2] NullPointerException in PanelMeter.transformNeedle(PanelMeter.java:163)

### ISSUE THREAD

**Issue by SanAndreaP** [malte0811/IndustrialWires#17]
So I got a crash when looking at the Panel Meter:
```
java.lang.NullPointerException: Tesselating block model
	at malte0811.industrialWires.controlpanel.PanelMeter.transformNeedle(PanelMeter.java:163)
	at malte0811.industrialWires.controlpanel.PanelMeter.transformNumber(PanelMeter.java:149)
	at malte0811.industrialWires.controlpanel.PanelMeter.getQuads(PanelMeter.java:121)
	at malte0811.industrialWires.controlpanel.PanelUtils.generateQuads(PanelUtils.java:87)
	at malte0811.industrialWires.client.panelmodel.PanelModel$AssembledBakedModel.func_188616_a(PanelModel.java:128)
	at malte0811.industrialWires.client.panelmodel.PanelModel.func_188616_a(PanelModel.java:76)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)
```

full logs:
https://gist.github.com/SanAndreasP/442c1d6641f1543b293e1d8aa9705d0f

**Comment by malte0811** [comment]
Should be fixed for the next release, together with a couple of other NPE's in getQuads. All of them are stupid race conditions that only happen under reasonably heavy load, which is why I never saw them before. I'll try to get the release out today or tomorrow.
