### ISSUE TITLE
[Control Panel]CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by Remering** [malte0811/IndustrialWires#87]
# How did I do
I'm playing on a server.
When I place the control panel, it looks great.
![image](https://user-images.githubusercontent.com/26853503/88159887-80da8800-cc40-11ea-93ab-9081b5368ed0.png)
But when I begin to rotate the autotransformer, textures are lost and I get a CCL error.
![image](https://user-images.githubusercontent.com/26853503/88160182-e62e7900-cc40-11ea-9ad0-aba0f6a4b731.png)
![image](https://user-images.githubusercontent.com/26853503/88160303-0bbb8280-cc41-11ea-89a5-c4b8719088b0.png)
# CCL error log
```
[17:18:01] [Chunk Batcher 39/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-134, y:66, z:-341
  Block Class:   class malte0811.industrialwires.blocks.controlpanel.BlockPanel
  Registry Name: industrialwires:control_panel
  Metadata:      0
  State:         industrialwires:control_panel[facing=down,type=top]
 Tile at position
  Tile Class:    class malte0811.industrialwires.blocks.controlpanel.TileEntityPanel
  Tile Id:       industrialwires:control_panel
  Tile NBT:      {components:[{color:254,rsInput:0,panelHeight:0.0f,rsChannel:6b,x:0.40625f,rsId:0,y:0.78125f,type:"7seg"},{color:16711680,panelHeight:0.0f,rsChannel:0b,x:0.875f,active:0b,rsId:0,y:0.84375f,type:"lighted_button",timeout:0,latching:0b},{color:0,panelHeight:0.0f,x:0.6171875f,y:0.71875f,text:"Adjust",type:"label"},{color:16515072,rsInput:0,panelHeight:0.0f,rsChannel:1b,x:0.3125f,rsId:0,y:0.46875f,type:"7seg"},{color:64512,rsInput:1,panelHeight:0.0f,rsChannel:0b,x:0.3125f,rsId:0,y:0.15625f,type:"7seg"},{output:16,rsChannel2:4b,panelHeight:0.0f,rsChannel:0b,x:0.59375f,rsId:0,y:0.78125f,type:"variac",rsId2:0},{rsChannel2:6b,wide:0b,rsInput:0,panelHeight:0.0f,rsChannel:2b,x:0.0625f,rsId:0,y:0.75f,type:"panel_meter",rsId2:0},{color:16580608,rsInput:0,panelHeight:0.0f,rsChannel:5b,x:0.40625f,rsId:0,y:0.46875f,type:"7seg"},{rsChannel2:5b,wide:0b,rsInput:0,panelHeight:0.0f,rsChannel:1b,x:0.0625f,rsId:0,y:0.4375f,type:"panel_meter",rsId2:0},{color:0,panelHeight:0.0f,x:0.0625f,y:0.0625f,text:"Setting",type:"label"},{rsChannel2:4b,wide:0b,rsInput:16,panelHeight:0.0f,rsChannel:0b,x:0.0625f,rsId:0,y:0.125f,type:"panel_meter",rsId2:0},{color:65024,rsInput:0,panelHeight:0.0f,rsChannel:4b,x:0.40625f,rsId:0,y:0.15625f,type:"7seg"},{color:253,rsInput:0,panelHeight:0.0f,rsChannel:2b,x:0.3125f,rsId:0,y:0.78125f,type:"7seg"},{color:0,panelHeight:0.0f,x:0.0703125f,y:0.375f,text:"RS Signal",type:"label"},{color:0,panelHeight:0.0f,x:0.0703125f,y:0.6875f,text:"Energy",type:"label"}],top:1,texture:{ForgeCaps:{"customnpcs:itemscripteddata":{}},id:"industrialwires:control_panel",Count:1b,Damage:2s},x:-134,angle:0.78037316f,facing:3,y:66,z:-341,id:"industrialwires:control_panel",height:0.50499994f}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.GL11.glBegin(GL11.java:680) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.renderer.GlStateManager.func_187447_r(GlStateManager.java:891) ~[bus.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78277_a(FontRenderer.java:381) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:305) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:585) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:708) ~[bip.class:?]
	at bre.smoothfont.FontRendererHook.drawStringHook(FontRendererHook.java:806) ~[FontRendererHook.class:?]
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:417) ~[bip.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:408) ~[bip.class:?]
	at malte0811.industrialwires.controlpanel.Label.getQuads(Label.java:72) ~[Label.class:?]
	at malte0811.industrialwires.controlpanel.PanelUtils.generateQuads(PanelUtils.java:87) ~[PanelUtils.class:?]
	at malte0811.industrialwires.client.panelmodel.PanelModel$AssembledBakedModel.func_188616_a(PanelModel.java:127) ~[PanelModel$AssembledBakedModel.class:?]
	at malte0811.industrialwires.client.panelmodel.PanelModel.func_188616_a(PanelModel.java:75) ~[PanelModel.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:158) ~[bvo.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 5 more
````

# System information:
```
Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1281421264 bytes (1222 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 12 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 68 mods loaded, 68 mods active
	Launched Version: HMCL 3.2.149
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国) (zh_CN)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```
# Mod information:
```
	| State  | ID                    | Version           | Source                                              | Signature                                |
	|:------ |:--------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                   | 9.42              | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                       | None                                     |
	| LCHIJA | forge                 | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                       | None                                     |
	| LCHIJA | anothercommonbugfix   | 1.1.0             | minecraft.jar                                       | None                                     |
	| LCHIJA | smoothfontcore        | mc1.12.2-2.1      | minecraft.jar                                       | None                                     |
	| LCHIJA | creativecoredummy     | 1.0.0             | minecraft.jar                                       | None                                     |
	| LCHIJA | jecharacters          | 1.12.0-3.4.7      | [通用拼音搜索]JustEnoughCharacters-1.12.0-3.4.7.jar       | None                                     |
	| LCHIJA | foamfixcore           | 7.7.4             | minecraft.jar                                       | None                                     |
	| LCHIJA | smoothfont            | mc1.12.2-2.1      | [平滑字体]SmoothFont.jar                                | None                                     |
	| LCHIJA | waila                 | 1.8.26            | [NEI]Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCHIJA | appliedenergistics2   | rv6-stable-7      | [应用能源]appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | extracells            | 2.6.5             | [AE2更多储存单元]ExtraCells-1.12.2-2.6.5.jar              | None                                     |
	| LCHIJA | jei                   | 4.15.0.268        | [JEI内置管理器]jei_1.12.2-4.15.0.2618.jar                | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55     | [匠魂]Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | baubles               | 1.5.2             | [神秘前置]Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26        | [神秘时代6]Thaumcraft-1.12.2-6.1.BETA26.jar             | None                                     |
	| LCHIJA | twilightforest        | 3.10.1013         | [暮色森林]twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.179 | [匠魂]TConstruct-1.12.2-2.13.0.179.jar                | None                                     |
	| LCHIJA | wailaharvestability   | 1.1.12            | [NEI]WailaHarvestability-mc1.12-1.1.12.jar          | None                                     |
	| LCHIJA | wawla                 | 2.5.270           | [NEI]Wawla-1.12.2-2.5.270.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | customnpcs            | 1.12              | [NPC主体]CustomNPCs_1.12.2-(01Oct19).jar              | None                                     |
	| LCHIJA | variedcommodities     | 1.12.2            | [NPC杂项]VariedCommodities_1.12.2(21nov19).jar        | None                                     |
	| LCHIJA | foamfix               | 0.10.10-1.12.2    | [内存优化]foamfix-0.10.10-1.12.2.jar                    | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358         | [前置]CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | moartinkers           | 0.6.0             | [匠魂更多材料]moartinkers-0.6.0.jar                       | None                                     |
	| LCHIJA | chunkanimator         | 1.2               | [区块加载美化]ChunkAnimator-MC1.12-1.2.jar                | None                                     |
	| LCHIJA | vexview               | 2.6.10            | [可视化]VexView_ForgeMod_1.12+.jar                     | None                                     |
	| LCHIJA | recipehandler         | 0.13              | [合成冲突消除]NoMoreRecipeConflict-0.13(1.12.2).jar       | None                                     |
	| LCHIJA | crafttweaker          | 4.1.19            | [女装MOD]CraftTweaker2-1.12-4.1.19.jar                | None                                     |
	| LCHIJA | ctgui                 | 1.0.0             | [女装MOD]CraftTweaker2-1.12-4.1.19.jar                | None                                     |
	| LCHIJA | crafttweakerjei       | 2.0.3             | [女装MOD]CraftTweaker2-1.12-4.1.19.jar                | None                                     |
	| LCHIJA | ic2                   | 2.8.188-ex112     | [工业2]industrialcraft-2-2.8.188-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | gravisuite            | 3.1.1             | [工业2附属重力装甲]Gravitation+Suite-3.1.1.jar              | None                                     |
	| LCHIJA | advanced_solar_panels | 4.3.0             | [工业2附属高级太阳能]Advanced+Solar+Panels-4.3.0.jar         | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r32        | [拔刀]SlashBlade-mc1.12-r32.jar                       | None                                     |
	| LCHIJA | mm_lib                | 1.3.0             | [拔刀樱前置]MMLib-1.3.0.jar                              | None                                     |
	| LCHIJA | sakura                | 0.0.9.4-1.12.2    | [拔刀樱]Sakura-0.0.9.4-1.12.2.jar                      | None                                     |
	| LCHIJA | slashblade_addon      | 1.4.0             | [拔刀附属]SJAP_V1.4.0_MC1.12.2.jar                      | None                                     |
	| LCHIJA | lastsmith             | V1.2.6.5-MC1.12.2 | [拔刀附属最后的太刀匠人]TLS-V1.2.6.5-MC1.12.2.jar              | None                                     |
	| LCHIJA | slashbladetic         | V1.1.0-MC1.12.2   | [拔刀附属匠魂]SlashBladeTic-V1.1.0-MC1.12.2.jar           | None                                     |
	| LCHIJA | negorerouse           | r1                | [拔刀附属尼格洛茨·诸神帝裔]NegoreRouse-r1.1.4-mc1.12.2.jar      | None                                     |
	| LCHIJA | foxex                 | 1.0.0             | [拔刀附属狐月刀]FoxExtra[1.12.2]v1.0.jar                   | None                                     |
	| LCHIJA | journeymap            | 1.12-5.4.9        | [旅行者地图]journeymap-1.12-5.4.9.jar                    | None                                     |
	| LCHIJA | avaritia              | 3.3.0             | [无尽贪婪]Avaritia-1.12.2-3.3.0.33-universal.jar        | None                                     |
	| LCHIJA | wanionlib             | 1.12.2-2.2        | [无尽附属奇点前置]WanionLib.jar                             | None                                     |
	| LCHIJA | eternalsingularity    | 1.12.2-.1.0.5     | [无尽附属永恒奇点]EternalSingularity.jar                    | None                                     |
	| LCHIJA | armourers_workshop    | 1.12.2-0.49.1     | [时装工坊]Armourers-Workshop-1.12.2-0.49.1.jar          | None                                     |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844 | [更多箱子]ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | botania               | r1.10-361         | [植物魔法]Botania+r1.10-361.jar                         | None                                     |
	| LCHIJA | extrabotany           | 57                | [植物魔法额外]ExtraBotany-r1.1-57.jar                     | None                                     |
	| LCHIJA | i18nmod               | 1.12.2-1.0.8      | [汉化]i18nupdatemod-1.12.2-1.0.8.jar                  | None                                     |
	| LCHIJA | immersiveengineering  | 0.12-92           | [沉浸工程]ImmersiveEngineering-0.12-92.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | immersivepetroleum    | 1.1.9             | [沉浸原油]immersivepetroleum-1.12.2-1.1.9.jar           | None                                     |
	| LCHIJA | immersivetech         | 1.3.10            | [沉浸科技]immersivetech-1.12-1.3.10.jar                 | None                                     |
	| LCHIJA | surge                 | 2.0.77            | [潮汐]Surge-1.12.2-2.0.77.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | audiobuffer           | 1.0.0             | [点歌]AudioBuffer-1.0.jar                             | None                                     |
	| LCHIJA | customskinloader      | 14.11             | [皮肤补丁]CustomSkinLoader_Forge-14.11.jar              | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LCHIJA | infernalmobs          | 1.7.5             | [精英怪]InfernalMobs-1.12.2.jar                        | None                                     |
	| LCHIJA | opframe               | 1.4.0             | [网络相册]OnlinePicFrame_v1.4.37_mc1.12.2.jar           | None                                     |
	| LCHIJA | creativecore          | 1.10.0            | [网络相册前置]CreativeCore_v1.10.10_mc1.12.2.jar          | None                                     |
	| LCHIJA | custommainmenu        | 2.0.9.1           | [自定义]CustomMainMenu-MC1.12.2-2.0.9.1.jar            | None                                     |
	| LCHIJA | torohealthmod         | 1.12.2-11         | [血量]torohealth-1.12.2-11.jar                        | None                                     |
	| LCHIJA | nshowmod              | 1.1               | [血量显示]NShowMod-1.12.2.jar                           | None                                     |
	| LCHIJA | jeresources           | 0.9.2.58          | JustEnoughResources-1.12.2-0.9.2.58.jar             | None                                     |
	| LCHIJA | nei                   | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | industrialwires       | 1.7-36            | [沉浸线缆]IndustrialWires-1.7-36.jar                    | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCHIJA | phosphor-lighting     | 1.12.2-0.2.4      | [照明优化]phosphor-1.12.2-0.2.4+build46-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
AnotherCommonBugFix ([修复]AnotherCommonBugFix-1.1.0-1.12.2.jar)
  com.anotherera.core.ACBFClassTransformer
JechCore ([通用拼音搜索]JustEnoughCharacters-1.12.0-3.4.7.jar)
  me.towdium.jecharacters.core.JechClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([内存优化]foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
PhosphorFMLLoadingPlugin ([照明优化]phosphor-1.12.2-0.2.4+build46-universal.jar)
  
CorePlugin ([平滑字体]SmoothFont.jar)
  bre.smoothfont.asm.Transformer
CustomSkinLoader ([皮肤补丁]CustomSkinLoader_Forge-14.11.jar)
  customskinloader.forge.loader.LaunchWrapper
SurgeLoadingPlugin ([潮汐]Surge-1.12.2-2.0.77.jar)
  
CreativePatchingLoader ([网络相册前置]CreativeCore_v1.10.10_mc1.12.2.jar)
  
LoadingPlugin ([区块加载美化]ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 446.14' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Armourer's Workshop: 
		Baking Queue: 0
		Request Queue: 0
		Texture Paint Type: TEXTURE_REPLACE
		Multipass Skin Rendering: true
	Render Layers:
		 Render Class: net.minecraft.client.renderer.entity.RenderPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			net.optifine.player.PlayerItemsLayer
			baubles.client.BaublesRenderLayer
			vazkii.botania.client.core.handler.ContributorFancinessHandler
			vazkii.botania.client.core.handler.BaubleRenderHandler
			vazkii.botania.client.render.entity.LayerGaiaHead
			com.meteor.extrabotany.client.render.CosmeticItemRenderLayer
			blusunrize.immersiveengineering.client.render.IEBipedLayerRenderer
			mods.flammpfeil.slashblade.client.renderer.entity.layers.LayerSlashBlade
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
		 Render Class: net.minecraft.client.renderer.entity.RenderPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			net.optifine.player.PlayerItemsLayer
			baubles.client.BaublesRenderLayer
			vazkii.botania.client.core.handler.ContributorFancinessHandler
			vazkii.botania.client.core.handler.BaubleRenderHandler
			vazkii.botania.client.render.entity.LayerGaiaHead
			com.meteor.extrabotany.client.render.CosmeticItemRenderLayer
			blusunrize.immersiveengineering.client.render.IEBipedLayerRenderer
			mods.flammpfeil.slashblade.client.renderer.entity.layers.LayerSlashBlade
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer

```
# OpenGL Information
```
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by Remering** [comment]
I got the same issue in the single player world
